"""Add financial_data and growth_metrics tables

Revision ID: c98801dc3194
Revises: 
Create Date: 2026-01-26 22:40:18.615424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98801dc3194'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_data',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_end', sa.Date(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('operating_profit', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('net_profit_margin', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_assets', sa.Float(), nullable=True),
    sa.Column('current_liabilities', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_payout', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_financial_data_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_data')),
    sa.UniqueConstraint('stock_id', 'fiscal_year', name='uq_financial_stock_year')
    )
    op.create_index('ix_financial_fiscal_year', 'financial_data', ['fiscal_year'], unique=False)
    op.create_index('ix_financial_stock_year', 'financial_data', ['stock_id', 'fiscal_year'], unique=False)
    op.create_table('growth_metrics',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sales_cagr_1y', sa.Float(), nullable=True),
    sa.Column('sales_cagr_3y', sa.Float(), nullable=True),
    sa.Column('sales_cagr_5y', sa.Float(), nullable=True),
    sa.Column('sales_cagr_10y', sa.Float(), nullable=True),
    sa.Column('profit_cagr_1y', sa.Float(), nullable=True),
    sa.Column('profit_cagr_3y', sa.Float(), nullable=True),
    sa.Column('profit_cagr_5y', sa.Float(), nullable=True),
    sa.Column('profit_cagr_10y', sa.Float(), nullable=True),
    sa.Column('roe_1y', sa.Float(), nullable=True),
    sa.Column('roe_3y', sa.Float(), nullable=True),
    sa.Column('roe_5y', sa.Float(), nullable=True),
    sa.Column('roe_10y', sa.Float(), nullable=True),
    sa.Column('roce_1y', sa.Float(), nullable=True),
    sa.Column('roce_3y', sa.Float(), nullable=True),
    sa.Column('roce_5y', sa.Float(), nullable=True),
    sa.Column('roce_10y', sa.Float(), nullable=True),
    sa.Column('roa_1y', sa.Float(), nullable=True),
    sa.Column('roa_3y', sa.Float(), nullable=True),
    sa.Column('roa_5y', sa.Float(), nullable=True),
    sa.Column('roa_10y', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('low_52w', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_growth_metrics_stock_id_stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_metrics')),
    sa.UniqueConstraint('stock_id', 'snapshot_date', name='uq_growth_stock_date')
    )
    op.create_index('ix_growth_snapshot_date', 'growth_metrics', ['snapshot_date'], unique=False)
    op.create_index('ix_growth_stock_date', 'growth_metrics', ['stock_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_growth_stock_date', table_name='growth_metrics')
    op.drop_index('ix_growth_snapshot_date', table_name='growth_metrics')
    op.drop_table('growth_metrics')
    op.drop_index('ix_financial_stock_year', table_name='financial_data')
    op.drop_index('ix_financial_fiscal_year', table_name='financial_data')
    op.drop_table('financial_data')
    # ### end Alembic commands ###
